### PR TITLE
Added a sort option

### PR DESCRIPTION
**Pull request by guillaumev**
Allow users to sort through the API (I will add another PR in trailpack-webserver)

### CODE REVIEW

**Comment by guillaumev** [comment]
@konstantinzolotarev would it be possible to create a 0.4.4 release including this PR merged ? Thanks.

**Comment by konstantinzolotarev** [comment]
@guillaumev done. Will be released after tests will pass.

**Comment by guillaumev** [comment]
@konstantinzolotarev Thanks a lot ! If by any chance you can move this one forward as well: https://github.com/trailsjs/trailpack-webserver/pull/34

**Comment by konstantinzolotarev** [comment]
@guillaumev merged. Thank you

**Pull request merged**
