### PR TITLE
Added a count method to FootprintService

### PR DESCRIPTION
**Pull request by guillaumev**

### CODE REVIEW

**Comment by konstantinzolotarev** [comment]
@guillaumev good idea but actually `trailpack-footprints` doesn't support routing for `count` method. And this method would be useful only inside trails application.

Sorry if I missed PR for `footprints` trailpack that implements this functionality.

**Comment by guillaumev** [comment]
@konstantinzolotarev The idea for me is not to use this method for a route, but to add an "X-Total-Count" in the find footprints that will allow the API to return the total number of results when doing a find. I don't mind implementing this in trailpack-footprints, but would need to make sure that the count method is merged at least in trailpack-mongoose to make sure the approach is validated

**Comment by konstantinzolotarev** [comment]
@guillaumev Seems reasonable.
@scott-wyatt @tjwebb @trailsjs/maintainers What do you think about adding `count` method into other DB adapters ?

**Comment by jaumard** [comment]
https://github.com/trailsjs/trails/issues/34 at some point we planned this :) ^^ personally I think it's a good idea

**Comment by konstantinzolotarev** [comment]
Then I'll merge PR for now. And update other trailpacks in future.
@guillaumev Thank you !

**Pull request merged**
